### ISSUE TITLE
Missing package opencensus in ray-core?

### ISSUE THREAD

**Issue by Maltimore** [conda-forge/ray-packages-feedstock#16]
Sorry for not using the big issue template, I think this error is quite easy to reproduce.

I created a new environment with 

```
mamba create -n test ray-core
```
Then on ```ray.init()```:

```
$ python
Python 3.9.5 (default, Jun  4 2021, 12:28:51)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
```

I get a huge error message that finally tells me it tried to import opencensus and failed.

Installing opencensus with ```mamba install opencensus``` fixes the problem.

**Comment by h-vetinari** [comment]
So I'm trying this in #17, and it isn't giving an error. I saw you modified your environment a bit - do you still get the same error _just_  with `ray-core` in the environment?

**Comment by Maltimore** [comment]
Yep, I anticipated that you would ask this :) That's why in the meantime I created an environment with just `ray-core` and the

**Comment by Maltimore** [comment]
Closed accidentally.

I also tried whether the issue was using `mamba` instead of `conda`, but it isn't. Here's a log of a full fresh install:

```
$ conda create -n mytest ray-core
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/maltimore/miniconda3/envs/mytest

  added / updated specs:
    - ray-core


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.9.4               |hffdb5ce_0_cpython        27.4 MB  conda-forge
    setuptools-49.6.0          |   py39hf3d152e_3         943 KB  conda-forge
    tk-8.6.10                  |       h21135ba_1         3.2 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        31.5 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  aiohttp            conda-forge/linux-64::aiohttp-3.7.4.post0-py39h3811e60_0
  aiohttp-cors       conda-forge/noarch::aiohttp-cors-0.7.0-py_0
  aioredis           conda-forge/noarch::aioredis-1.3.1-py_0
  async-timeout      conda-forge/noarch::async-timeout-3.0.1-py_1000
  attrs              conda-forge/noarch::attrs-21.2.0-pyhd8ed1ab_0
  blessings          conda-forge/linux-64::blessings-1.7-py39hf3d152e_1004
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py39h3811e60_1001
  c-ares             conda-forge/linux-64::c-ares-1.17.1-h7f98852_1
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.5.30-ha878542_0
  certifi            conda-forge/linux-64::certifi-2021.5.30-py39hf3d152e_0
  cffi               conda-forge/linux-64::cffi-1.14.5-py39he32792d_0
  chardet            conda-forge/linux-64::chardet-4.0.0-py39hf3d152e_1
  click              conda-forge/linux-64::click-8.0.1-py39hf3d152e_0
  colorama           conda-forge/noarch::colorama-0.4.4-pyh9f0ad1d_0
  colorful           conda-forge/noarch::colorful-0.5.4-pyhd8ed1ab_0
  cryptography       conda-forge/linux-64::cryptography-3.4.7-py39hbca0aa6_0
  filelock           conda-forge/noarch::filelock-3.0.12-pyh9f0ad1d_0
  gpustat            conda-forge/noarch::gpustat-0.6.0-pyhd8ed1ab_1
  grpcio             conda-forge/linux-64::grpcio-1.38.0-py39hff7568b_0
  hiredis            conda-forge/linux-64::hiredis-1.1.0-py39h07f9747_1
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  importlib-metadata conda-forge/linux-64::importlib-metadata-4.5.0-py39hf3d152e_0
  jsonschema         conda-forge/noarch::jsonschema-3.2.0-pyhd8ed1ab_3
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35.1-hea4e1c9_2
  libblas            conda-forge/linux-64::libblas-3.9.0-9_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-9_openblas
  libffi             conda-forge/linux-64::libffi-3.3-h58526e2_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h2828fa1_19
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-9.3.0-hff62375_19
  libgfortran5       conda-forge/linux-64::libgfortran5-9.3.0-hff62375_19
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h2828fa1_19
  liblapack          conda-forge/linux-64::liblapack-3.9.0-9_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.15-pthreads_h8fe5266_1
  libprotobuf        conda-forge/linux-64::libprotobuf-3.17.2-h780b84a_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h6de172a_19
  msgpack-python     conda-forge/linux-64::msgpack-python-1.0.2-py39h1a9c180_1
  multidict          conda-forge/linux-64::multidict-5.1.0-py39h3811e60_1
  ncurses            conda-forge/linux-64::ncurses-6.2-h58526e2_4
  numpy              conda-forge/linux-64::numpy-1.20.3-py39hdbf815f_1
  nvidia-ml          conda-forge/noarch::nvidia-ml-7.352.0-py_0
  openssl            conda-forge/linux-64::openssl-1.1.1k-h7f98852_0
  pip                conda-forge/noarch::pip-21.1.2-pyhd8ed1ab_0
  prometheus_client  conda-forge/noarch::prometheus_client-0.11.0-pyhd8ed1ab_0
  protobuf           conda-forge/linux-64::protobuf-3.17.2-py39he80948d_0
  psutil             conda-forge/linux-64::psutil-5.8.0-py39h3811e60_1
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyopenssl          conda-forge/noarch::pyopenssl-20.0.1-pyhd8ed1ab_0
  pyrsistent         conda-forge/linux-64::pyrsistent-0.17.3-py39h3811e60_2
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py39hf3d152e_3
  python             conda-forge/linux-64::python-3.9.4-hffdb5ce_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.9-1_cp39
  pyyaml             conda-forge/linux-64::pyyaml-5.4.1-py39h3811e60_0
  ray-core           conda-forge/linux-64::ray-core-1.2.0-py39h714431f_0
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  redis-py           conda-forge/noarch::redis-py-3.5.3-pyh9f0ad1d_0
  requests           conda-forge/noarch::requests-2.25.1-pyhd3deb0d_0
  setproctitle       conda-forge/linux-64::setproctitle-1.1.10-py39h3811e60_1004
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py39hf3d152e_3
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sqlite             conda-forge/linux-64::sqlite-3.35.5-h74cdb3f_0
  tk                 conda-forge/linux-64::tk-8.6.10-h21135ba_1
  typing-extensions  conda-forge/noarch::typing-extensions-3.10.0.0-hd8ed1ab_0
  typing_extensions  conda-forge/noarch::typing_extensions-3.10.0.0-pyha770c72_0
  tzdata             conda-forge/noarch::tzdata-2021a-he74cb21_0
  urllib3            conda-forge/noarch::urllib3-1.26.5-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  yaml               conda-forge/linux-64::yaml-0.2.5-h516909a_0
  yarl               conda-forge/linux-64::yarl-1.6.3-py39h3811e60_1
  zipp               conda-forge/noarch::zipp-3.4.1-pyhd8ed1ab_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-3.9.4         | 27.4 MB   | ################################################################################################################################################### | 100%
setuptools-49.6.0    | 943 KB    | ################################################################################################################################################### | 100%
tk-8.6.10            | 3.2 MB    | ################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate mytest
#
# To deactivate an active environment, use
#
#     $ conda deactivate

[ 2021-06-18 14:20:38 ] [ @maltinator ] [ ~ ] [ master ]
$ conda activate mytest
[ 2021-06-18 14:20:44 ] [ @maltinator ] [ ~ ] [ master ]
$ python -c "import ray; ray.init()"
2021-06-18 14:20:52,234 INFO services.py:1172 -- View the Ray dashboard at http://127.0.0.1:8265
2021-06-18 14:20:54,918 WARNING worker.py:1107 -- The agent on node maltinator failed with the following error:
Traceback (most recent call last):
  File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/agent.py", line 323, in <module>
    loop.run_until_complete(agent.run())
  File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/agent.py", line 138, in run
    modules = self._load_modules()
  File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/agent.py", line 87, in _load_modules
    agent_cls_list = dashboard_utils.get_all_modules(
  File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/utils.py", line 208, in get_all_modules
    importlib.import_module(name)
  File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 21, in <module>
    from ray.metrics_agent import MetricsAgent, Gauge, Record
  File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/metrics_agent.py", line 10, in <module>
    from opencensus.stats import aggregation
ModuleNotFoundError: No module named 'opencensus'

(raylet) Traceback (most recent call last):
(raylet)   File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/agent.py", line 334, in <module>
(raylet)     raise e
(raylet)   File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/agent.py", line 323, in <module>
(raylet)     loop.run_until_complete(agent.run())
(raylet)   File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
(raylet)     return future.result()
(raylet)   File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/agent.py", line 138, in run
(raylet)     modules = self._load_modules()
(raylet)   File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/agent.py", line 87, in _load_modules
(raylet)     agent_cls_list = dashboard_utils.get_all_modules(
(raylet)   File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/utils.py", line 208, in get_all_modules
(raylet)     importlib.import_module(name)
(raylet)   File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/importlib/__init__.py", line 127, in import_module
(raylet)     return _bootstrap._gcd_import(name[level:], package, level)
(raylet)   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
(raylet)   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
(raylet)   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
(raylet)   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
(raylet)   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
(raylet)   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
(raylet)   File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 21, in <module>
(raylet)     from ray.metrics_agent import MetricsAgent, Gauge, Record
(raylet)   File "/home/maltimore/miniconda3/envs/mytest/lib/python3.9/site-packages/ray/metrics_agent.py", line 10, in <module>
(raylet)     from opencensus.stats import aggregation
(raylet) ModuleNotFoundError: No module named 'opencensus'
```

**Comment by Maltimore** [comment]
Thank you so much, @h-vetinari for looking into this in-depth in #17.
I see now that this error is probably platform dependent and I should've provided more information immediately. If you need any additional information, please let me know.

**Comment by vnlitvinov** [comment]
@h-vetinari I found that we dropped requiring `opencensus` in https://github.com/conda-forge/ray-packages-feedstock/pull/8 for some unknown reason... (more specifically, this is the commit that drops it: https://github.com/conda-forge/ray-packages-feedstock/pull/8/commits/cd7d3340cb602b0e9cbed32b7ce30e776ed58b13)

**Comment by vnlitvinov** [comment]
@Maltimore new build of Ray 1.2.0 is now up on conda-forge.
